import Head from "next/head";
import {
  FirstSection,
  Jobs,
  Lessons,
  StartUp,
  Team,
  Projects,
  Partners,
} from "../components";
export default function Home() {
  return (
    <>
      {/* need to write good CEO */}
      <Head>
        <title>Developer Azerbaijan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>
      <FirstSection />
      <Lessons />
      <StartUp />
      <Jobs />
      <Team />
      <Projects />
      <Partners />
    </>
  );
}
